steps:

  - task: UseDotNet@2
    displayName: 'Install .net core 8.0'
    inputs:
      packageType: sdk
      version: '8.0.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet
  
  - task: NuGetAuthenticate@1
    displayName: NuGet Authenticate

